### ISSUE TITLE
Make LBRY.fund Terms Of Use

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry.fund#11]
lbry.fund currently has Terms of Use link on he footer but if i click this link it will going to the top page. would be nice if have this page..

**Comment by alyssaoc** [comment]
@jsigwart Do we have a terms page for fund?

**Comment by jsigwart** [comment]
This is part of the same issue as on lbry.io: https://github.com/lbryio/lbry.io/issues/430 https://github.com/lbryio/lbry.io/issues/369

**Comment by alyssaoc** [comment]
closed for issues on lbryio #430 and #369
