### ISSUE TITLE
make privacy policy page of LBRY.Fund

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry.fund#12]
lbry.fund currently has privacy policy link on he footer but if i click this link it will going to the top page. would be nice if have this page..

**Comment by alyssaoc** [comment]
@jsigwart Is this a broken link or do we have this page somewhere?

**Comment by jsigwart** [comment]
Same issue as  https://github.com/lbryio/lbry.io/issues/430 https://github.com/lbryio/lbry.io/issues/369

**Comment by alyssaoc** [comment]
closed for issues on lbry.io #430 and #369
