### ISSUE TITLE
lbry.fund creator page (just final edits in comment thread)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.fund#17]
The new lbry.io nav drives creators to lbry.fund.

It would be good to have a landing page specifically oriented for creators.

**Comment by kauffj** [comment]
@jsigwart feasible to do something simple here before EOD Monday?

**Comment by jsigwart** [comment]
I will have this done EOD today.

**Comment by jsigwart** [comment]
What's the Call to Action here?

**Comment by kauffj** [comment]
This page should be a landing page explaining how lbry.fund supports creators and convincing them to apply.

It could:

- Explain the program, with a creator oriented focus
- Have a creator specific submission form
- Highlight past grants
- Answer FAQs

**Comment by jeanlucaslima** [comment]
@kauffj is the content already defined/written somewhere? If so, I could asssign this issue to me and create the page.

**Comment by REMINGTON-HOLDER** [comment]
I can help work on some HTML and CSS if needed. I have not forked this yet so I am curious if we are allowed or specified anywhere what front-end frameworks we are allowed to use if any.

**Comment by jsigwart** [comment]
@REMINGTON-HOLDER LBRY.fund is just a static site on Github pages, so some of the functions are limited.

**Comment by kauffj** [comment]
@Feanor78 to review

**Comment by kauffj** [comment]
https://lbry.fund/creator.html

**Comment by Feanor78** [comment]
Feedback/copy edits here:
https://docs.google.com/document/d/1-L-Xe5ciKXMWiZb_OAQ4NbZo4ByRsaGfC4dgIoji7sU/edit?usp=sharing
