### ISSUE TITLE
Google: Mobile usability issues detected

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.fund#24]
> Search Console has identified that your site is affected by 2 new Mobile Usability related issues. This means that Mobile Usability may be negatively affected in Google Search results. We encourage you to fix these issues.
>
> **Top new issues found, ordered by number of affected pages:**
>
> Text too small to read
> Clickable elements too close together

**Comment by kauffj** [comment]
@finer9 will give @NetOperatorWibby access to google web console or whatever tool gives more details

**Comment by finer9** [comment]
Let me know if this helps https://search.google.com/test/mobile-friendly

**Comment by NetOperatorWibby** [comment]
No issues!
